version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: 
              name: "Build Production"
              command: |
                cd ea-usageTracking-gui/ClientApp
                npm run build-production
workflows:
    build-and-test:
      jobs:
        - build