version: 2.1
jobs:
  build-and-deploy:
    parameters:
      stage:
        type: string
    working_directory: ~/usage
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: Build
          command: |
            ls
            cd ./ea-usageTracking-gui/ClientApp
            npm install @angular/cli          
            npm run build-<< parameters.stage >>
      - run:
          name: Deploy
          command: |
            cd ./ea-usageTracking-gui/ClientApp/dist
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v
            cf api https://api.london.cloud.service.gov.uk
            cf auth "$CF_USERNAME" "$CF_PASSWORD"
            cf target
            echo "$CF_SPACE" 
            cf target -o DOF-DSS  -s << parameters.space >> 
            cf push
workflows:
  build-deploy-sandbox:
    jobs:
      - build-and-deploy:
          space: "sandbox"
          context: govuk-paas-sandbox