version: 2.1
jobs:
  build:
    working_directory: ~/usage
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install
            npm install @angular/cli
            npm i cloudfoundry-cli
      - run:
          name: Build
          command: |
            ls
            cd ./ea-usageTracking-gui/ClientApp
            npm run build-production
      - run:
          name: Deploy
          command: |
            cd ./ea-usageTracking-gui/ClientApp/dist
            cf push