version: 2.1
jobs:
  build:
    working_directory: ~/usage
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: Build
          command: |
            ls
            cd ./ea-usageTracking-gui/ClientApp
            npm install @angular/cli          
            npm run build-production
      - run:
          name: Deploy
          command: |
            cd ./ea-usageTracking-gui/ClientApp/dist
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v